name: Develop & Snapshot

on:
  push:
    branches:
      - "develop"

jobs:
  build-and-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: "1.11.1.1155"

      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}

      - name: Install npm
        run: npm install

      - name: Run All Tests and Snapshot
        run: clojure -T:build ci :snapshot true

      - name: Deploy Snapshot
        run: clojure -T:build deploy :snapshot true
        env:
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: "1.11.1.1155"

      - name: Install npm
        run: npm install

      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Run Tests
        run: clojure -T:build test
